// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: lcd

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_MainPanel;
extern lv_obj_t * ui_PanelHaut;
extern lv_obj_t * ui_PanelStatus;
extern lv_obj_t * ui_LabelStatus;
extern lv_obj_t * ui_ButtonStatus;
extern lv_obj_t * ui_LabelStatusValue;
extern lv_obj_t * ui_LabelModeValue;
extern lv_obj_t * ui_LabelMode;
extern lv_obj_t * ui_ImageMis;
extern lv_obj_t * ui_LabelNBMValue;
extern void ui_event_PanelIMU(lv_event_t * e);
extern lv_obj_t * ui_PanelIMU;
extern lv_obj_t * ui_ImageIMU;
extern lv_obj_t * ui_LabelAngIMU;
extern lv_obj_t * ui_LabelIMU;
extern lv_obj_t * ui_PanelBat;
extern lv_obj_t * ui_LabelBat;
extern void ui_event_ArcBat(lv_event_t * e);
extern lv_obj_t * ui_ArcBat;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_PanelBas;
extern lv_obj_t * ui_PanelBaro;
extern lv_obj_t * ui_LabelInfo;
extern lv_obj_t * ui_LabelVSpeed;
extern lv_obj_t * ui_LabelAlt;
extern lv_obj_t * ui_LabelPress;
extern lv_obj_t * ui_LabelTemp;
extern lv_obj_t * ui_AltVal;
extern lv_obj_t * ui_VSpeedVal;
extern lv_obj_t * ui_PresVal;
extern lv_obj_t * ui_TempVal;
extern lv_obj_t * ui_PanelGPS;
extern lv_obj_t * ui_LabelGPS;
extern lv_obj_t * ui_LabelLat;
extern lv_obj_t * ui_LabelLong;
extern lv_obj_t * ui_LabelSpeed;
extern lv_obj_t * ui_LabelDate;
extern lv_obj_t * ui_LabelTime;
extern lv_obj_t * ui_TimeVal;
extern lv_obj_t * ui_DateVal;
extern lv_obj_t * ui_SpeedVal;
extern lv_obj_t * ui_LongVal;
extern lv_obj_t * ui_LatVal;
extern void ui_event_PanelMag(lv_event_t * e);
extern lv_obj_t * ui_PanelMag;
extern lv_obj_t * ui_LabelMag;
extern lv_obj_t * ui_LabelAngMag;
extern lv_obj_t * ui_ImageMAG;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

