// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: lcd

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_MainPanel = NULL;
lv_obj_t * ui_PanelHaut = NULL;
lv_obj_t * ui_PanelStatus = NULL;
lv_obj_t * ui_LabelStatus = NULL;
lv_obj_t * ui_ButtonStatus = NULL;
lv_obj_t * ui_LabelStatusValue = NULL;
lv_obj_t * ui_LabelModeValue = NULL;
lv_obj_t * ui_LabelMode = NULL;
lv_obj_t * ui_ImageMis = NULL;
lv_obj_t * ui_LabelNBMValue = NULL;
lv_obj_t * ui_PanelIMU = NULL;
lv_obj_t * ui_ImageIMU = NULL;
lv_obj_t * ui_LabelAngIMU = NULL;
lv_obj_t * ui_LabelIMU = NULL;
lv_obj_t * ui_PanelBat = NULL;
lv_obj_t * ui_LabelBat = NULL;
lv_obj_t * ui_ArcBat = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_PanelBas = NULL;
lv_obj_t * ui_PanelBaro = NULL;
lv_obj_t * ui_LabelInfo = NULL;
lv_obj_t * ui_LabelVSpeed = NULL;
lv_obj_t * ui_LabelAlt = NULL;
lv_obj_t * ui_LabelPress = NULL;
lv_obj_t * ui_LabelTemp = NULL;
lv_obj_t * ui_AltVal = NULL;
lv_obj_t * ui_VSpeedVal = NULL;
lv_obj_t * ui_PresVal = NULL;
lv_obj_t * ui_TempVal = NULL;
lv_obj_t * ui_PanelGPS = NULL;
lv_obj_t * ui_LabelGPS = NULL;
lv_obj_t * ui_LabelLat = NULL;
lv_obj_t * ui_LabelLong = NULL;
lv_obj_t * ui_LabelSpeed = NULL;
lv_obj_t * ui_LabelDate = NULL;
lv_obj_t * ui_LabelTime = NULL;
lv_obj_t * ui_TimeVal = NULL;
lv_obj_t * ui_DateVal = NULL;
lv_obj_t * ui_SpeedVal = NULL;
lv_obj_t * ui_LongVal = NULL;
lv_obj_t * ui_LatVal = NULL;
lv_obj_t * ui_PanelMag = NULL;
lv_obj_t * ui_LabelMag = NULL;
lv_obj_t * ui_LabelAngMag = NULL;
lv_obj_t * ui_ImageMAG = NULL;
// event funtions
void ui_event_PanelIMU(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ChangAngle_Animation(ui_ImageIMU, 0);
    }
}

void ui_event_ArcBat(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_Label9, target, "", "%");
    }
}

void ui_event_PanelMag(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ChangAngle_Animation(ui_ImageMAG, 0);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Screen1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x14151B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Screen1, lv_color_hex(0x404040), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Screen1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_Screen1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Screen1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Screen1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Screen1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Screen1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Screen1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_MainPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_MainPanel, lv_pct(100));
    lv_obj_set_height(ui_MainPanel, lv_pct(100));
    lv_obj_set_align(ui_MainPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_MainPanel, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_MainPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MainPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainPanel, lv_color_hex(0x0A0064), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_MainPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MainPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MainPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MainPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_MainPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_MainPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelHaut = lv_obj_create(ui_MainPanel);
    lv_obj_set_width(ui_PanelHaut, lv_pct(100));
    lv_obj_set_height(ui_PanelHaut, lv_pct(50));
    lv_obj_set_align(ui_PanelHaut, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelHaut, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelHaut, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelHaut, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelHaut, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelHaut, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelStatus = lv_obj_create(ui_PanelHaut);
    lv_obj_set_width(ui_PanelStatus, lv_pct(33));
    lv_obj_set_height(ui_PanelStatus, lv_pct(100));
    lv_obj_set_align(ui_PanelStatus, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelStatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelStatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelStatus = lv_label_create(ui_PanelStatus);
    lv_obj_set_width(ui_LabelStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelStatus, 58);
    lv_obj_set_y(ui_LabelStatus, 17);
    lv_label_set_text(ui_LabelStatus, "STATUS");
    lv_obj_set_style_text_color(ui_LabelStatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelStatus, &ui_font_Display24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonStatus = lv_btn_create(ui_PanelStatus);
    lv_obj_set_width(ui_ButtonStatus, 20);
    lv_obj_set_height(ui_ButtonStatus, 20);
    lv_obj_set_x(ui_ButtonStatus, -64);
    lv_obj_set_y(ui_ButtonStatus, -44);
    lv_obj_set_align(ui_ButtonStatus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonStatus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonStatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonStatus, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonStatus, lv_color_hex(0x08EF2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonStatus, lv_color_hex(0xC61D1D), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_ButtonStatus, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_ButtonStatus, lv_color_hex(0xD31B1B), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_ButtonStatus, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_ButtonStatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(ui_ButtonStatus, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_color(ui_ButtonStatus, lv_color_hex(0x120375), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_opa(ui_ButtonStatus, 255, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_color(ui_ButtonStatus, lv_color_hex(0x680316), LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_bg_opa(ui_ButtonStatus, 255, LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_bg_color(ui_ButtonStatus, lv_color_hex(0x026B05), LV_PART_MAIN | LV_STATE_USER_4);
    lv_obj_set_style_bg_opa(ui_ButtonStatus, 255, LV_PART_MAIN | LV_STATE_USER_4);

    ui_LabelStatusValue = lv_label_create(ui_PanelStatus);
    lv_obj_set_width(ui_LabelStatusValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelStatusValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelStatusValue, 5);
    lv_obj_set_y(ui_LabelStatusValue, -47);
    lv_obj_set_align(ui_LabelStatusValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelStatusValue, "ARMED");
    lv_obj_set_style_text_color(ui_LabelStatusValue, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelStatusValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelStatusValue, &ui_font_Display24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelModeValue = lv_label_create(ui_PanelStatus);
    lv_obj_set_width(ui_LabelModeValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelModeValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelModeValue, -29);
    lv_obj_set_y(ui_LabelModeValue, 20);
    lv_obj_set_align(ui_LabelModeValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelModeValue, "STABILIZE");
    lv_obj_set_style_text_color(ui_LabelModeValue, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelModeValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelModeValue, &ui_font_Display24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMode = lv_label_create(ui_PanelStatus);
    lv_obj_set_width(ui_LabelMode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMode, -48);
    lv_obj_set_y(ui_LabelMode, -13);
    lv_obj_set_align(ui_LabelMode, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMode, "mode");
    lv_obj_set_style_text_color(ui_LabelMode, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LabelMode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelMode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_LabelMode, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMode, &ui_font_Display16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageMis = lv_img_create(ui_PanelStatus);
    lv_img_set_src(ui_ImageMis, &ui_img_nucleaire_png);
    lv_obj_set_width(ui_ImageMis, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageMis, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageMis, -57);
    lv_obj_set_y(ui_ImageMis, 78);
    lv_obj_set_align(ui_ImageMis, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageMis, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageMis, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelNBMValue = lv_label_create(ui_PanelStatus);
    lv_obj_set_width(ui_LabelNBMValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNBMValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNBMValue, -3);
    lv_obj_set_y(ui_LabelNBMValue, 76);
    lv_obj_set_align(ui_LabelNBMValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNBMValue, "50");
    lv_obj_set_style_text_color(ui_LabelNBMValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelNBMValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelNBMValue, &ui_font_Display24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelIMU = lv_obj_create(ui_PanelHaut);
    lv_obj_set_width(ui_PanelIMU, lv_pct(33));
    lv_obj_set_height(ui_PanelIMU, lv_pct(100));
    lv_obj_set_align(ui_PanelIMU, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelIMU, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelIMU, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelIMU, lv_color_hex(0x1F1D25), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelIMU, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelIMU, lv_color_hex(0x14151B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelIMU, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelIMU, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageIMU = lv_img_create(ui_PanelIMU);
    lv_img_set_src(ui_ImageIMU, &ui_img_avion_png);
    lv_obj_set_width(ui_ImageIMU, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageIMU, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageIMU, -6);
    lv_obj_set_y(ui_ImageIMU, 31);
    lv_obj_set_align(ui_ImageIMU, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageIMU, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageIMU, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImageIMU, 160);

    ui_LabelAngIMU = lv_label_create(ui_PanelIMU);
    lv_obj_set_width(ui_LabelAngIMU, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAngIMU, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAngIMU, 1);
    lv_obj_set_y(ui_LabelAngIMU, -64);
    lv_obj_set_align(ui_LabelAngIMU, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelAngIMU, "0 °");
    lv_obj_set_style_text_color(ui_LabelAngIMU, lv_color_hex(0xF29849), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelAngIMU, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelAngIMU, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelIMU = lv_label_create(ui_PanelIMU);
    lv_obj_set_width(ui_LabelIMU, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelIMU, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelIMU, -11);
    lv_obj_set_y(ui_LabelIMU, -99);
    lv_obj_set_align(ui_LabelIMU, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelIMU, "IMU");
    lv_obj_set_style_text_color(ui_LabelIMU, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelIMU, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelIMU, &ui_font_Display24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelBat = lv_obj_create(ui_PanelHaut);
    lv_obj_set_width(ui_PanelBat, lv_pct(33));
    lv_obj_set_height(ui_PanelBat, lv_pct(100));
    lv_obj_set_align(ui_PanelBat, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelBat, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelBat, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelBat, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelBat = lv_label_create(ui_PanelBat);
    lv_obj_set_width(ui_LabelBat, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBat, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBat, -3);
    lv_obj_set_y(ui_LabelBat, -95);
    lv_obj_set_align(ui_LabelBat, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBat, "BATTERY");
    lv_obj_set_style_text_color(ui_LabelBat, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBat, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBat, &ui_font_Display24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcBat = lv_arc_create(ui_PanelBat);
    lv_obj_set_width(ui_ArcBat, 150);
    lv_obj_set_height(ui_ArcBat, 150);
    lv_obj_set_x(ui_ArcBat, -4);
    lv_obj_set_y(ui_ArcBat, 13);
    lv_obj_set_align(ui_ArcBat, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_ArcBat, 100);
    lv_arc_set_bg_angles(ui_ArcBat, 270, 269);
    lv_obj_set_style_arc_color(ui_ArcBat, lv_color_hex(0xFF6640), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcBat, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcBat, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcBat, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcBat, lv_color_hex(0x10DD20), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcBat, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcBat, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcBat, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcBat, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_ArcBat);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -1);
    lv_obj_set_y(ui_Label9, 0);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "100%");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelBas = lv_obj_create(ui_MainPanel);
    lv_obj_set_width(ui_PanelBas, lv_pct(100));
    lv_obj_set_height(ui_PanelBas, lv_pct(50));
    lv_obj_set_x(ui_PanelBas, 414);
    lv_obj_set_y(ui_PanelBas, -46);
    lv_obj_set_align(ui_PanelBas, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelBas, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_PanelBas, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelBas, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelBas, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelBas, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelBaro = lv_obj_create(ui_PanelBas);
    lv_obj_set_width(ui_PanelBaro, lv_pct(33));
    lv_obj_set_height(ui_PanelBaro, lv_pct(100));
    lv_obj_set_align(ui_PanelBaro, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelBaro, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelBaro, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelBaro, lv_color_hex(0x1F1D25), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelBaro, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelBaro, lv_color_hex(0x14151B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelBaro, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelBaro, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelInfo = lv_label_create(ui_PanelBaro);
    lv_obj_set_width(ui_LabelInfo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelInfo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelInfo, -6);
    lv_obj_set_y(ui_LabelInfo, -90);
    lv_obj_set_align(ui_LabelInfo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelInfo, "INFORMATIONS");
    lv_obj_set_style_text_color(ui_LabelInfo, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelInfo, &ui_font_Display24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelVSpeed = lv_label_create(ui_PanelBaro);
    lv_obj_set_width(ui_LabelVSpeed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelVSpeed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelVSpeed, -66);
    lv_obj_set_y(ui_LabelVSpeed, 0);
    lv_obj_set_align(ui_LabelVSpeed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelVSpeed, "VERT. SPEED");
    lv_obj_set_style_text_color(ui_LabelVSpeed, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelVSpeed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelVSpeed, &ui_font_Display24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelAlt = lv_label_create(ui_PanelBaro);
    lv_obj_set_width(ui_LabelAlt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAlt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAlt, -81);
    lv_obj_set_y(ui_LabelAlt, -44);
    lv_obj_set_align(ui_LabelAlt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelAlt, "ALTITUDE");
    lv_obj_set_style_text_color(ui_LabelAlt, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelAlt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelAlt, &ui_font_Display24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPress = lv_label_create(ui_PanelBaro);
    lv_obj_set_width(ui_LabelPress, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPress, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPress, -78);
    lv_obj_set_y(ui_LabelPress, 40);
    lv_obj_set_align(ui_LabelPress, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPress, "PRESSURE");
    lv_obj_set_style_text_color(ui_LabelPress, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPress, &ui_font_Display24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTemp = lv_label_create(ui_PanelBaro);
    lv_obj_set_width(ui_LabelTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTemp, -59);
    lv_obj_set_y(ui_LabelTemp, 85);
    lv_obj_set_align(ui_LabelTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTemp, "TEMPERATURE");
    lv_obj_set_style_text_color(ui_LabelTemp, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTemp, &ui_font_Display24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AltVal = lv_label_create(ui_PanelBaro);
    lv_obj_set_width(ui_AltVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AltVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AltVal, 72);
    lv_obj_set_y(ui_AltVal, -46);
    lv_obj_set_align(ui_AltVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AltVal, "123 m");
    lv_obj_set_style_text_color(ui_AltVal, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AltVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AltVal, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VSpeedVal = lv_label_create(ui_PanelBaro);
    lv_obj_set_width(ui_VSpeedVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VSpeedVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VSpeedVal, 80);
    lv_obj_set_y(ui_VSpeedVal, -2);
    lv_obj_set_align(ui_VSpeedVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VSpeedVal, "5 m/s");
    lv_obj_set_style_text_color(ui_VSpeedVal, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VSpeedVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VSpeedVal, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresVal = lv_label_create(ui_PanelBaro);
    lv_obj_set_width(ui_PresVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PresVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresVal, 64);
    lv_obj_set_y(ui_PresVal, 39);
    lv_obj_set_align(ui_PresVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PresVal, "1013 hPa");
    lv_obj_set_style_text_color(ui_PresVal, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresVal, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempVal = lv_label_create(ui_PanelBaro);
    lv_obj_set_width(ui_TempVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempVal, 80);
    lv_obj_set_y(ui_TempVal, 83);
    lv_obj_set_align(ui_TempVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempVal, "24 °C");
    lv_obj_set_style_text_color(ui_TempVal, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TempVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempVal, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelGPS = lv_obj_create(ui_PanelBas);
    lv_obj_set_width(ui_PanelGPS, lv_pct(33));
    lv_obj_set_height(ui_PanelGPS, lv_pct(100));
    lv_obj_set_align(ui_PanelGPS, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelGPS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelGPS, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelGPS, lv_color_hex(0x1F1D25), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelGPS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelGPS, lv_color_hex(0x14151B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelGPS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelGPS, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelGPS = lv_label_create(ui_PanelGPS);
    lv_obj_set_width(ui_LabelGPS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelGPS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelGPS, -14);
    lv_obj_set_y(ui_LabelGPS, -89);
    lv_obj_set_align(ui_LabelGPS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelGPS, "GPS");
    lv_obj_set_style_text_color(ui_LabelGPS, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelGPS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelGPS, &ui_font_Display24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelLat = lv_label_create(ui_PanelGPS);
    lv_obj_set_width(ui_LabelLat, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLat, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLat, -82);
    lv_obj_set_y(ui_LabelLat, -45);
    lv_obj_set_align(ui_LabelLat, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLat, "LATITUDE");
    lv_obj_set_style_text_color(ui_LabelLat, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelLat, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelLat, &ui_font_Display24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelLong = lv_label_create(ui_PanelGPS);
    lv_obj_set_width(ui_LabelLong, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLong, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLong, -77);
    lv_obj_set_y(ui_LabelLong, -11);
    lv_obj_set_align(ui_LabelLong, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLong, "LONGITUDE");
    lv_obj_set_style_text_color(ui_LabelLong, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelLong, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelLong, &ui_font_Display24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSpeed = lv_label_create(ui_PanelGPS);
    lv_obj_set_width(ui_LabelSpeed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSpeed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSpeed, -94);
    lv_obj_set_y(ui_LabelSpeed, 23);
    lv_obj_set_align(ui_LabelSpeed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSpeed, "SPEED");
    lv_obj_set_style_text_color(ui_LabelSpeed, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSpeed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSpeed, &ui_font_Display24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDate = lv_label_create(ui_PanelGPS);
    lv_obj_set_width(ui_LabelDate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDate, -99);
    lv_obj_set_y(ui_LabelDate, 62);
    lv_obj_set_align(ui_LabelDate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDate, "DATE");
    lv_obj_set_style_text_color(ui_LabelDate, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDate, &ui_font_Display24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTime = lv_label_create(ui_PanelGPS);
    lv_obj_set_width(ui_LabelTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTime, -101);
    lv_obj_set_y(ui_LabelTime, 94);
    lv_obj_set_align(ui_LabelTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTime, "Time");
    lv_obj_set_style_text_color(ui_LabelTime, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTime, &ui_font_Display24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeVal = lv_label_create(ui_PanelGPS);
    lv_obj_set_width(ui_TimeVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeVal, 73);
    lv_obj_set_y(ui_TimeVal, 97);
    lv_obj_set_align(ui_TimeVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeVal, "19:18:21");
    lv_obj_set_style_text_color(ui_TimeVal, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TimeVal, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DateVal = lv_label_create(ui_PanelGPS);
    lv_obj_set_width(ui_DateVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DateVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DateVal, 48);
    lv_obj_set_y(ui_DateVal, 62);
    lv_obj_set_align(ui_DateVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DateVal, "25-08-2025");
    lv_obj_set_style_text_color(ui_DateVal, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DateVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DateVal, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedVal = lv_label_create(ui_PanelGPS);
    lv_obj_set_width(ui_SpeedVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpeedVal, 67);
    lv_obj_set_y(ui_SpeedVal, 24);
    lv_obj_set_align(ui_SpeedVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpeedVal, "25 km/h");
    lv_obj_set_style_text_color(ui_SpeedVal, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpeedVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpeedVal, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LongVal = lv_label_create(ui_PanelGPS);
    lv_obj_set_width(ui_LongVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LongVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LongVal, 75);
    lv_obj_set_y(ui_LongVal, -11);
    lv_obj_set_align(ui_LongVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LongVal, "12.345");
    lv_obj_set_style_text_color(ui_LongVal, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LongVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LongVal, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LatVal = lv_label_create(ui_PanelGPS);
    lv_obj_set_width(ui_LatVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LatVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LatVal, 73);
    lv_obj_set_y(ui_LatVal, -46);
    lv_obj_set_align(ui_LatVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LatVal, "12.345");
    lv_obj_set_style_text_color(ui_LatVal, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LatVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LatVal, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelMag = lv_obj_create(ui_PanelBas);
    lv_obj_set_width(ui_PanelMag, lv_pct(33));
    lv_obj_set_height(ui_PanelMag, lv_pct(100));
    lv_obj_set_align(ui_PanelMag, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelMag, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelMag, lv_color_hex(0x1F1D25), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelMag, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelMag, lv_color_hex(0x14151B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelMag, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelMag, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMag = lv_label_create(ui_PanelMag);
    lv_obj_set_width(ui_LabelMag, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMag, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMag, 3);
    lv_obj_set_y(ui_LabelMag, -92);
    lv_obj_set_align(ui_LabelMag, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMag, "MAGNRTOMETER");
    lv_obj_set_style_text_color(ui_LabelMag, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMag, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMag, &ui_font_Display24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelAngMag = lv_label_create(ui_PanelMag);
    lv_obj_set_width(ui_LabelAngMag, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAngMag, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAngMag, -2);
    lv_obj_set_y(ui_LabelAngMag, 63);
    lv_obj_set_align(ui_LabelAngMag, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelAngMag, "0 °");
    lv_obj_set_style_text_color(ui_LabelAngMag, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelAngMag, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelAngMag, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageMAG = lv_img_create(ui_PanelMag);
    lv_img_set_src(ui_ImageMAG, &ui_img_nord_png);
    lv_obj_set_width(ui_ImageMAG, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageMAG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageMAG, -1);
    lv_obj_set_y(ui_ImageMAG, -10);
    lv_obj_set_align(ui_ImageMAG, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageMAG, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageMAG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_ImageMAG, 3600);
    lv_img_set_zoom(ui_ImageMAG, 100);

    lv_obj_add_event_cb(ui_PanelIMU, ui_event_PanelIMU, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ArcBat, ui_event_ArcBat, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelMag, ui_event_PanelMag, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_MainPanel = NULL;
    ui_PanelHaut = NULL;
    ui_PanelStatus = NULL;
    ui_LabelStatus = NULL;
    ui_ButtonStatus = NULL;
    ui_LabelStatusValue = NULL;
    ui_LabelModeValue = NULL;
    ui_LabelMode = NULL;
    ui_ImageMis = NULL;
    ui_LabelNBMValue = NULL;
    ui_PanelIMU = NULL;
    ui_ImageIMU = NULL;
    ui_LabelAngIMU = NULL;
    ui_LabelIMU = NULL;
    ui_PanelBat = NULL;
    ui_LabelBat = NULL;
    ui_ArcBat = NULL;
    ui_Label9 = NULL;
    ui_PanelBas = NULL;
    ui_PanelBaro = NULL;
    ui_LabelInfo = NULL;
    ui_LabelVSpeed = NULL;
    ui_LabelAlt = NULL;
    ui_LabelPress = NULL;
    ui_LabelTemp = NULL;
    ui_AltVal = NULL;
    ui_VSpeedVal = NULL;
    ui_PresVal = NULL;
    ui_TempVal = NULL;
    ui_PanelGPS = NULL;
    ui_LabelGPS = NULL;
    ui_LabelLat = NULL;
    ui_LabelLong = NULL;
    ui_LabelSpeed = NULL;
    ui_LabelDate = NULL;
    ui_LabelTime = NULL;
    ui_TimeVal = NULL;
    ui_DateVal = NULL;
    ui_SpeedVal = NULL;
    ui_LongVal = NULL;
    ui_LatVal = NULL;
    ui_PanelMag = NULL;
    ui_LabelMag = NULL;
    ui_LabelAngMag = NULL;
    ui_ImageMAG = NULL;

}
